name: Docker preact deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker preact deploy
      run: docker build . --file Dockerfile --tag preact-deploy:$(date +%s)
